# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: UserManagement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ntspbms618db
    username: root
    password: safari
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect 
      ddl-auto: update
    generate-ddl: true
    
   
user:
   module:
         message:
            save-success: User is Registered with id
            save-failure: User is not registered
            update-success: User is updated successfully
            update-failure: User not found for deletion
            delete-success: User deleted successfully
            delete-failure: User not found for deletion

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

